# Generated by Django 2.2.12 on 2021-10-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0002_auto_20211005_1816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='components',
            new_name='Component',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='components_text',
            new_name='component_text',
        ),
    ]
