# Generated by Django 2.2.12 on 2021-10-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0003_auto_20211005_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='hostname',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='component',
            name='status',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.DeleteModel(
            name='status',
        ),
    ]
