# Generated by Django 3.2.7 on 2021-12-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0005_auto_20211208_2033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='authuser',
            name='institution',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
