# Generated by Django 3.2.7 on 2021-12-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0006_auto_20211224_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authgrouppermissions',
            name='group',
        ),
        migrations.RemoveField(
            model_name='authgrouppermissions',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='authpermission',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='authusergroups',
            name='group',
        ),
        migrations.RemoveField(
            model_name='authusergroups',
            name='user',
        ),
        migrations.RemoveField(
            model_name='authuseruserpermissions',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='authuseruserpermissions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='djangoadminlog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='djangoadminlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
    ]
