# Generated by Django 3.2.7 on 2021-12-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0007_auto_20211224_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
